### PR TITLE
fix InjectCookies and InjectSetCookieHeader. Solves #30

### PR DESCRIPTION
**Pull request by highfredo**

### CODE REVIEW

**Comment by ilike2burnthing** [comment]
Thanks for this.

I'm just maintaining these repos while the actual dev is away. Can you explain how to test this with Jackett, as currently we just point to a nuget package - https://github.com/Jackett/Jackett/blob/723173d2381b52a9f2bfa4fc180c82d021d39d0c/src/Jackett.Common/Jackett.Common.csproj#L18

**Comment by highfredo** [comment]
To be able to test easily I implemented an alternative version of ClearanceHandler in jackett

https://github.com/highfredo/Jackett/commit/cdc351ee3ab01e55a91301b178626adcd48e4846

I know it's not the best way to test it, but I couldn't get Jackett to use a local version of FlareSolverrSharp...

**Comment by ilike2burnthing** [comment]
Would you be able to upload your FlareSolverrSharp fork to nuget.org? Similar to FFace32's - https://www.nuget.org/packages/FlareSolverrSharp-fork

Ideally I'd like to test the actual changes being made.

Failing that though, I'll use your Jackett build above.

**Comment by highfredo** [comment]
here you go https://www.nuget.org/packages/FlareSolverrSharp-fix-30/

**Comment by ilike2burnthing** [comment]
Thanks. Wolfmax4k isn't currently presenting Cloudflare challenges, so I can't test with that, but it has partially resolved https://github.com/Jackett/Jackett/issues/15164 (I'll go into detail there shortly).

**Pull request merged**
